terraform {
  required_providers {
    yandex = {
      source = "yandex-cloud/yandex"
    }
  }
  required_version = ">= 0.13"
}

provider "yandex" {
  cloud_id                 = var.cloud_id
  folder_id                = var.folder_id
  zone                     = var.zone1
  service_account_key_file = var.key_file
}

module "vpc" {
  source    = "./modules/vpc"
  folder_id = var.folder_id
}

module "web" {
  source       = "./modules/web"
  image_id     = var.image_id
  folder_id    = var.folder_id
  network_1_id = module.vpc.network_1_id
  subnet_1_id  = module.vpc.subnet_1_id
  subnet_2_id  = module.vpc.subnet_2_id
}

module "zbx" {
  source       = "./modules/zbx"
  image_id     = var.image_id
  folder_id    = var.folder_id
  network_1_id = module.vpc.network_1_id
  subnet_1_id  = module.vpc.subnet_1_id
  subnet_2_id  = module.vpc.subnet_2_id
  zbx_db_user  = var.zbx_db_user
  zbx_db_name  = var.zbx_db_name
}

#module "elk" {
#  source           = "./modules/vpc"
#  cloud_id = var.cloud_id
#  image_id = var.image_id
#  folder_id = var.folder_id
#}

module "jump" {
  source           = "./modules/jump"
  image_id         = var.image_id
  folder_id        = var.folder_id
  instance_fqdn    = module.web.instance_fqdn
  network_1_id     = module.vpc.network_1_id
  subnet_1_id      = module.vpc.subnet_1_id
  subnet_2_id      = module.vpc.subnet_2_id
  pgsql_cluster_id = module.zbx.pgsql_cluster_id
}

resource "local_file" "tf-ansible-vars" {
  content  = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.

    zbx_db_user: ${var.zbx_db_user}
    zbx_db_name: ${var.zbx_db_name}
    zbx_db_password: ${module.zbx.zbx_db_password}
    zbx_db_cluster: c-${module.zbx.pgsql_cluster_id}.rw.mdb.yandexcloud.net
    zbx_server_fqdn: ${module.zbx.zbx_server_fqdn}
    DOC
  filename = "./tf_ansible_vars_file.yml"
}



