---
- name: --- Install zabbix server ---
  hosts: zbxsrv
  gather_facts: false
  become: true
  vars_files:
    - ../tf_ansible_vars_file.yml

  pre_tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:

    - name: Gathering facts
      ansible.builtin.setup:

    - name: Wait for /var/lib/dpkg/lock-frontend to be released 
      ansible.builtin.shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;

  roles:
    - role: community.zabbix.zabbix_server
      zabbix_server_dbport: 6432
      zabbix_server_dbhost_run_install: false
      zabbix_server_database_creation: false

### Zabbix frontend ###
- name: --- Install zabbix frontend ---
  hosts: zbxfe
  gather_facts: false
  become: true
  vars_files:
    - ../tf_ansible_vars_file.yml

  pre_tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:

    - name: Gathering facts
      ansible.builtin.setup:

    - name: Wait for /var/lib/dpkg/lock-frontend to be released 
      ansible.builtin.shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;

  roles:
    - role: geerlingguy.apache

    - role: geerlingguy.php

    - role: community.zabbix.zabbix_web
      zabbix_api_server_url: "{{ ansible_hostname }}"
      zabbix_server_dbport: 6432
      zabbix_server_dbhost_run_install: false
      zabbix_server_database_creation: false

### Zabbix agent for server ###
- name: --- Install zabbix agent on server ---
  hosts: zbxsrv
  gather_facts: false
  become: true
  vars_files:
    - ../tf_ansible_vars_file.yml

  pre_tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:

    - name: Gathering facts
      ansible.builtin.setup:

    - name: Wait for /var/lib/dpkg/lock-frontend to be released 
      ansible.builtin.shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;

  roles:
    - role: community.zabbix.zabbix_agent
      become: false
      zabbix_agent_become_on_localhost: true
      zabbix_agent_server: localhost
      zabbix_agent_serveractive: localhost
      zabbix_agent_ip: 127.0.0.1
      zabbix_api_server_port: 80
      zabbix_api_login_user: Admin
      zabbix_api_login_pass: zabbix
      zabbix_api_create_hostgroup: true
      zabbix_api_create_hosts: true
      zabbix_host_groups:
        - Linux servers
        - Zabbix servers
      zabbix_agent_link_templates:
        - Linux by Zabbix agent
        - Zabbix server health

### Zabbix agent for nginx  ###
- name: --- Install zabbix agent on nginx ---
  hosts: web
  gather_facts: false
  vars_files:
    - ../tf_ansible_vars_file.yml

  pre_tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:

    - name: Gathering facts
      ansible.builtin.setup:

    - name: Wait for /var/lib/dpkg/lock-frontend to be released 
      ansible.builtin.shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;

  roles:
    - role: community.zabbix.zabbix_agent
      become: false
      zabbix_agent_become_on_localhost: true
      zabbix_api_server_port: 80
      zabbix_api_login_user: Admin
      zabbix_api_login_pass: zabbix
      zabbix_api_create_hostgroup: true
      zabbix_api_create_hosts: true
      zabbix_host_groups:
        - Linux servers
        - Nginx servers
      zabbix_agent_link_templates:
        - Linux by Zabbix agent
        - Nginx by Zabbix agent

### Zabbix agent for others ###
- name: --- Install zabbix agent on others ---
  hosts: all,!zbxsrv,!web
  gather_facts: false
  vars_files:
    - ../tf_ansible_vars_file.yml

  pre_tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:

    - name: Gathering facts
      ansible.builtin.setup:

    - name: Wait for /var/lib/dpkg/lock-frontend to be released 
      ansible.builtin.shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;

  roles:
    - role: community.zabbix.zabbix_agent
      become: false
      zabbix_agent_become_on_localhost: true
      zabbix_api_server_port: 80
      zabbix_api_login_user: Admin
      zabbix_api_login_pass: zabbix
      zabbix_api_create_hostgroup: true
      zabbix_api_create_hosts: true
      zabbix_host_groups:
        - Linux servers
      zabbix_agent_link_templates:
        - Linux by Zabbix agent


### Zabbix dashboard ###
- name: --- Generate dashboard ---
  hosts: all
  gather_facts: false
  vars_files:
    - ../tf_ansible_vars_file.yml

  pre_tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:

    - name: Gathering facts
      ansible.builtin.setup:

  tasks:
    - name: Generate json
      delegate_to: localhost
      ansible.builtin.template:
        src: dashboard.json.j2
        dest: /tmp/dashboard.json
        mode: preserve

- name: --- Create zabbix dashboard ---
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../tf_ansible_vars_file.yml

  pre_tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:

    - name: Gathering facts
      ansible.builtin.setup:

    - name: Get token
      ansible.builtin.uri:
        url: http://{{ zabbix_api_server_host }}/zabbix/api_jsonrpc.php
        method: POST
        headers:
          Content-Type: application/json-rpc
        body: '{"jsonrpc":"2.0","method":"user.login","params":{"username":"Admin","password":"zabbix"},"id":1}'
        status_code: 200
        body_format: json
      register: token

    - name: Create dashboard
      ansible.builtin.uri:
        url: http://{{ zabbix_api_server_host }}/zabbix/api_jsonrpc.php
        method: POST
        headers:
          Content-Type: application/json-rpc
          Authorization: Bearer {{ token.json.result }}
        body: "{{ lookup('ansible.builtin.file', '/tmp/dashboard.json') }}"
        status_code: 200
        body_format: json
