---
- name: Install and start mysql
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:

    - name: Gathering facts
      ansible.builtin.setup:

  roles:
    - role: app
      app_pkg: mysql-server
      app_svc: mysql
