---
- name: --- Install zabbix frontend ---
  hosts: zbx-fe
  gather_facts: false
  vars_files:
    - ../tf_ansible_vars_file.yml

  pre_tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:

    - name: Gathering facts
      ansible.builtin.setup:

  tasks:
    - name: Install repo
      become: true
      ansible.builtin.apt:
        deb: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb

    - name: Install packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        name:
          - zabbix-frontend-php
          - php8.1-pgsql
          - zabbix-nginx-conf
        state: present
      notify: Enable and start service

    - name: Set nginx config
      become: true
      ansible.builtin.lineinfile:
        path: /etc/nginx/conf.d/zabbix.conf
        regexp: 'listen'
        line: "listen 8080;"
      notify: Restart service

    - name: Rewrite config files
      become: true
      ansible.builtin.template:
        src: zabbix.conf.php.j2
        dest: /etc/zabbix/web/zabbix.conf.php
        mode: preserve
      notify: Restart service

    - name: Give permissions to config files
      become: true
      ansible.builtin.file:
        path: /etc/zabbix/web/zabbix.conf.php
        owner: www-data
        group: www-data
        mode: '600'
      notify: Restart service

  handlers:
    - name: Enable and start service
      become: true
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - nginx
        - php8.1-fpm

    - name: Restart service
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
