---
- name: --- Install zabbix agent ---
  hosts: all,!zbx-srv
  gather_facts: false
  vars_files:
    - ../tf_ansible_vars_file.yml

  pre_tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:

    - name: Gathering facts
      ansible.builtin.setup:

  tasks:
    - name: Install repo
      become: true
      ansible.builtin.apt:
        deb: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb

    - name: Install packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        name:
          - zabbix-agent
        state: present
      notify: Enable and start service

    - name: Rewrite config file
      become: true
      ansible.builtin.template:
        src: zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
        mode: preserve
      notify: Restart service

  handlers:
    - name: Enable and start service
      become: true
      ansible.builtin.service:
        name: "zabbix-agent"
        enabled: true
        state: started

    - name: Restart service
      become: true
      ansible.builtin.service:
        name: "zabbix-agent"
        state: restarted
